// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCV-441wEsz0eczCE4QeFArPYZ8u9dilxk',
    appId: '1:1020007371342:web:7b4484738301a11f23e91f',
    messagingSenderId: '1020007371342',
    projectId: 'techvillage-91948',
    authDomain: 'techvillage-91948.firebaseapp.com',
    storageBucket: 'techvillage-91948.appspot.com',
    measurementId: 'G-LHBS9E5EYH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBgcpMapW7gMK6gz0MJ0PrNDlxgBdupZk0',
    appId: '1:1020007371342:android:9d9276f960717f4f23e91f',
    messagingSenderId: '1020007371342',
    projectId: 'techvillage-91948',
    storageBucket: 'techvillage-91948.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAv78BZhyr0F3AwZlYTZaLUmw-6BtyIJmY',
    appId: '1:1020007371342:ios:e3462b96bd5d066b23e91f',
    messagingSenderId: '1020007371342',
    projectId: 'techvillage-91948',
    storageBucket: 'techvillage-91948.appspot.com',
    iosClientId: '1020007371342-emq1ndmcffja0itk6qi3hq6e09btb52c.apps.googleusercontent.com',
    iosBundleId: 'com.example.techvillage',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAv78BZhyr0F3AwZlYTZaLUmw-6BtyIJmY',
    appId: '1:1020007371342:ios:e3462b96bd5d066b23e91f',
    messagingSenderId: '1020007371342',
    projectId: 'techvillage-91948',
    storageBucket: 'techvillage-91948.appspot.com',
    iosClientId: '1020007371342-emq1ndmcffja0itk6qi3hq6e09btb52c.apps.googleusercontent.com',
    iosBundleId: 'com.example.techvillage',
  );
}
